# Generated by Django 2.0 on 2020-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.CharField(max_length=200),
        ),
    ]
